package generate

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/vertex-language/go-cmake/eval"
	"github.com/vertex-language/go-cmake/toolchain"
)

// Tests are written out per directory, the way CMake writes them, because that
// is how a test run is scoped: `ctest` in a subdirectory of the build tree runs
// that subtree's tests and nothing else. One flat file would lose that, and
// losing it means a developer working on one component cannot run just its
// tests.

// CTest writes the per-directory test files for a configured project.
type CTest struct {
	State     *eval.State
	Graph     *Graph
	Toolchain *toolchain.Toolchain
	SourceDir string
	BinaryDir string
}

// TestFile is one directory's generated test file.
type TestFile struct {
	Path    string // absolute path of the file to write
	Content string
}

// Files renders every directory's test file. A directory with neither tests nor
// tested subdirectories produces nothing, so that an empty file never suggests
// tests that were not declared.
func (c *CTest) Files() []TestFile {
	// Group the tests by the directory that declared them.
	byDir := map[string][]eval.TestEntry{}
	for _, t := range c.State.Tests {
		byDir[t.BinaryDir] = append(byDir[t.BinaryDir], t)
	}

	var out []TestFile
	for _, dir := range c.State.AllDirs {
		children := c.testedChildren(dir, byDir)
		tests := byDir[dir.Binary]
		if len(tests) == 0 && len(children) == 0 {
			continue
		}
		out = append(out, TestFile{
			Path:    path.Join(dir.Binary, eval.TestFileName),
			Content: c.render(dir, tests, children),
		})
	}
	return out
}

// testedChildren names the subdirectories that have tests somewhere beneath
// them, so that the chain from the top reaches every test.
func (c *CTest) testedChildren(dir *eval.Directory, byDir map[string][]eval.TestEntry) []string {
	var out []string
	for _, child := range dir.Children {
		if c.hasTests(child, byDir) {
			rel := relativeTo(dir.Binary, child.Binary)
			if rel == "" {
				rel = path.Base(child.Binary)
			}
			out = append(out, rel)
		}
	}
	sort.Strings(out)
	return out
}

func (c *CTest) hasTests(dir *eval.Directory, byDir map[string][]eval.TestEntry) bool {
	if len(byDir[dir.Binary]) > 0 {
		return true
	}
	for _, child := range dir.Children {
		if c.hasTests(child, byDir) {
			return true
		}
	}
	return false
}

// render produces one directory's file.
func (c *CTest) render(dir *eval.Directory, tests []eval.TestEntry, children []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Test file generated by go-cmake. Do not edit.\n")
	fmt.Fprintf(&b, "# Source directory: %s\n", dir.Source)
	fmt.Fprintf(&b, "# Build directory: %s\n\n", dir.Binary)

	for _, t := range tests {
		fmt.Fprintf(&b, "add_test(%s%s)\n", t.Name, quotedArgs(c.resolveCommand(t.Command)))
		if props := c.propertiesOf(t.Name); props != "" {
			fmt.Fprintf(&b, "set_tests_properties(%s PROPERTIES%s)\n", t.Name, props)
		}
	}
	for _, child := range children {
		fmt.Fprintf(&b, "subdirs(%q)\n", child)
	}
	return b.String()
}

// propertiesOf renders the properties a test carries, in a stable order so that
// regenerating an unchanged project produces an unchanged file.
func (c *CTest) propertiesOf(name string) string {
	const prefix = "TEST:"
	var names []string
	for key := range c.State.Properties {
		if !strings.HasPrefix(key, prefix) {
			continue
		}
		rest := key[len(prefix):]
		testName, prop, found := strings.Cut(rest, ":")
		if found && testName == name {
			names = append(names, prop)
		}
	}
	sort.Strings(names)

	var b strings.Builder
	for _, prop := range names {
		fmt.Fprintf(&b, " %s %q", prop, c.State.Properties[prefix+name+":"+prop])
	}
	return b.String()
}

// resolveCommand replaces a target name with the file the build produced.
//
// add_test(NAME t COMMAND prog) names a target, not a program: at the point the
// test is declared the executable does not exist and its path is not yet
// decided. Substituting it here is what makes the generated test file runnable
// -- left alone, "prog" would be looked up on PATH, and would either not be
// found or, worse, find a different one.
func (c *CTest) resolveCommand(argv []string) []string {
	if c.Graph == nil || len(argv) == 0 {
		return argv
	}
	out := append([]string{}, argv...)
	for i, a := range out {
		if r, ok := c.Graph.Targets[a]; ok && r.Target.Type == "EXECUTABLE" {
			out[i] = targetOutputPath(r.Target, c.Toolchain, c.SourceDir, c.BinaryDir)
		}
	}
	return out
}

// quotedArgs renders a command as add_test's argument list. Every argument is
// quoted, because a test command routinely contains a path with a space in it
// and an unquoted one would silently become two arguments.
func quotedArgs(argv []string) string {
	var b strings.Builder
	for _, a := range argv {
		fmt.Fprintf(&b, " %q", a)
	}
	return b.String()
}

// WriteAll renders and writes every test file through a caller's writer.
func (c *CTest) WriteAll(write func(path string, content []byte) error) error {
	for _, f := range c.Files() {
		if err := write(f.Path, []byte(f.Content)); err != nil {
			return err
		}
	}
	return nil
}
