package generate

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/vertex-language/go-cmake/eval"
	"github.com/vertex-language/go-cmake/toolchain"
)

// An export is how one project becomes usable by another.
//
// A library that builds is not yet a library anyone can depend on. What makes
// it one is a file of add_library(... IMPORTED) calls carrying the same usage
// requirements the original target had -- its public headers, its definitions,
// what it links -- so that a consumer writes target_link_libraries(app
// Demo::util) and gets all of it. install(EXPORT) writes that file for the
// install tree and export() writes it for the build tree.
//
// The two differ in one thing only: what the paths inside are relative to. The
// build-tree file names the build directory outright, because the build
// directory is where the library is. The install-tree file computes a prefix
// from its own location at include time, because an installed package can be
// moved and the file has no way to know in advance where it will end up. That
// is the whole of the difference, so both come out of one generator.

// Export writes targets files for a resolved graph.
type Export struct {
	Graph     *Graph
	Toolchain *toolchain.Toolchain
	SourceDir string
	BinaryDir string
}

// BuildTreeFile is one file an export() asked for.
type BuildTreeFile struct {
	Path    string // absolute, inside the build tree
	Content string
}

// BuildTreeFiles renders every export() the project made.
func (e *Export) BuildTreeFiles() ([]BuildTreeFile, error) {
	var out []BuildTreeFile
	for _, req := range e.Graph.State.Exports {
		targets, err := e.membersOf(req)
		if err != nil {
			return nil, err
		}
		text, err := e.render(exportOptions{
			Targets:   targets,
			Namespace: req.Namespace,
			Install:   false,
		})
		if err != nil {
			return nil, err
		}
		file := req.File
		if !path.IsAbs(file) && !strings.Contains(file, ":") {
			file = path.Join(e.BinaryDir, file)
		}
		out = append(out, BuildTreeFile{Path: file, Content: text})
	}
	return out, nil
}

// membersOf resolves an export() to the targets it names, either directly or
// through the set they were installed under.
func (e *Export) membersOf(req eval.ExportRequest) ([]*eval.TargetState, error) {
	names := req.Targets
	if req.Set != "" {
		names = e.setMembers(req.Set)
		if len(names) == 0 {
			return nil, fmt.Errorf("export(EXPORT %s) names an export set no install(TARGETS) added to", req.Set)
		}
	}
	var out []*eval.TargetState
	for _, name := range names {
		r, ok := e.Graph.target(name)
		if !ok {
			return nil, fmt.Errorf("export() given unknown target %q", name)
		}
		out = append(out, r)
	}
	return out, nil
}

// setMembers lists the targets an export set holds, in declaration order so
// that the file is the same on every run.
func (e *Export) setMembers(set string) []string {
	var out []string
	for _, name := range e.Graph.Order {
		t := e.Graph.Targets[name].Target
		for _, s := range t.ExportSets {
			if s == set {
				out = append(out, name)
				break
			}
		}
	}
	return out
}

// exportOptions is what distinguishes one rendering from another.
type exportOptions struct {
	Targets   []*eval.TargetState
	Namespace string
	// Install selects the install-tree form: paths become relative to a prefix
	// the file works out for itself, and $<INSTALL_INTERFACE:> is the side of
	// an interface expression that applies.
	Install bool
	// PrefixDepth is how many directories up from the file the install prefix
	// is, for the install form.
	PrefixDepth int
	// IncludeDest is install(TARGETS ... INCLUDES DESTINATION), per target.
	IncludeDest map[string][]string
	// Destinations gives, per target, where its artifacts were installed.
	Destinations map[string]installedPaths
}

// installedPaths is where one target's files ended up under the prefix.
type installedPaths struct {
	// Location is the file a consumer runs or loads; Implib is the one it
	// links against, which on Windows is a different file for a shared library
	// and the same file everywhere else.
	Location string
	Implib   string
}

// render writes one targets file.
func (e *Export) render(opts exportOptions) (string, error) {
	var b strings.Builder
	names := make([]string, 0, len(opts.Targets))
	for _, t := range opts.Targets {
		names = append(names, opts.Namespace+t.Name)
	}

	b.WriteString("# Generated by go-cmake. Do not edit.\n\n")
	b.WriteString("cmake_policy(PUSH)\ncmake_policy(VERSION 3.16)\n\n")
	b.WriteString("set(CMAKE_IMPORT_FILE_VERSION 1)\n\n")
	writeInclusionGuard(&b, names)

	if opts.Install {
		writePrefixComputation(&b, opts.PrefixDepth)
	}

	config := e.Graph.State.GetVar("CMAKE_BUILD_TYPE")
	for _, t := range opts.Targets {
		if err := e.renderTarget(&b, t, opts, config); err != nil {
			return "", err
		}
	}

	if opts.Install {
		b.WriteString("unset(_IMPORT_PREFIX)\n\n")
	}
	b.WriteString("set(CMAKE_IMPORT_FILE_VERSION)\ncmake_policy(POP)\n")
	return b.String(), nil
}

// writeInclusionGuard reproduces CMake's own: a targets file may be included
// twice by two different consumers, and add_library() on a name that already
// exists is fatal. Returning early is right when every target is already
// there; a partial overlap means two different files claim the same names,
// which is a mistake worth stopping for.
func writeInclusionGuard(b *strings.Builder, names []string) {
	fmt.Fprintf(b, `set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS %s)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)

`, strings.Join(names, " "))
}

// writePrefixComputation walks up from the file to the install prefix.
//
// The file cannot be told where it will live: a package is built once and
// unpacked wherever somebody wants it, so the only thing it can rely on is its
// own path at the moment it is read.
func writePrefixComputation(b *strings.Builder, depth int) {
	b.WriteString("# Compute the installation prefix relative to this file.\n")
	b.WriteString(`get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)` + "\n")
	for i := 0; i < depth; i++ {
		b.WriteString(`get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)` + "\n")
	}
	b.WriteString("if(_IMPORT_PREFIX STREQUAL \"/\")\n  set(_IMPORT_PREFIX \"\")\nendif()\n\n")
}

// renderTarget writes one imported target: what it is, what a consumer
// inherits from it, and where its file is.
func (e *Export) renderTarget(b *strings.Builder, t *eval.TargetState, opts exportOptions, config string) error {
	full := opts.Namespace + t.Name
	fmt.Fprintf(b, "# Create imported target %s\n", full)
	switch t.Type {
	case "EXECUTABLE":
		fmt.Fprintf(b, "add_executable(%s IMPORTED)\n\n", full)
	case "INTERFACE":
		fmt.Fprintf(b, "add_library(%s INTERFACE IMPORTED)\n\n", full)
	case "SHARED", "MODULE", "STATIC", "OBJECT":
		fmt.Fprintf(b, "add_library(%s %s IMPORTED)\n\n", full, t.Type)
	default:
		fmt.Fprintf(b, "add_library(%s UNKNOWN IMPORTED)\n\n", full)
	}

	props, err := e.interfaceProperties(t, opts)
	if err != nil {
		return err
	}
	if len(props) > 0 {
		fmt.Fprintf(b, "set_target_properties(%s PROPERTIES\n", full)
		for _, p := range props {
			fmt.Fprintf(b, "  %s %q\n", p.name, p.value)
		}
		b.WriteString(")\n\n")
	}

	if t.Type == "INTERFACE" || t.Type == "UTILITY" {
		return nil // nothing is built, so there is no file to point at
	}

	loc, implib := e.artifactPaths(t, opts)
	if loc == "" {
		return nil
	}
	// Both the configuration-qualified properties and the plain ones are
	// written. CMake prefers the qualified pair when the consumer's
	// configuration matches one it was given and falls back to the plain one
	// otherwise, so writing both makes the file usable from a build whose
	// configuration this project never heard of.
	upper := strings.ToUpper(config)
	if upper == "" {
		upper = "NOCONFIG"
	}
	fmt.Fprintf(b, "set_property(TARGET %s APPEND PROPERTY IMPORTED_CONFIGURATIONS %s)\n", full, upper)
	fmt.Fprintf(b, "set_target_properties(%s PROPERTIES\n", full)
	if implib != "" {
		fmt.Fprintf(b, "  IMPORTED_IMPLIB_%s %q\n", upper, implib)
		fmt.Fprintf(b, "  IMPORTED_IMPLIB %q\n", implib)
	}
	fmt.Fprintf(b, "  IMPORTED_LOCATION_%s %q\n", upper, loc)
	fmt.Fprintf(b, "  IMPORTED_LOCATION %q\n", loc)
	b.WriteString(")\n\n")
	return nil
}

type exportProperty struct{ name, value string }

// interfaceProperties is what a consumer inherits by linking this target.
func (e *Export) interfaceProperties(t *eval.TargetState, opts exportOptions) ([]exportProperty, error) {
	ctx := &genexContext{
		graph:            e.Graph,
		tc:               e.Toolchain,
		target:           t,
		config:           e.Graph.State.GetVar("CMAKE_BUILD_TYPE"),
		installInterface: opts.Install,
	}

	includes, err := ctx.evalGenexList(t.IfaceIncludeDirs)
	if err != nil {
		return nil, err
	}
	if opts.Install {
		// $<INSTALL_INTERFACE:include> yields a path relative to the prefix,
		// which only means anything once the prefix is prepended.
		for i, dir := range includes {
			includes[i] = underPrefix(dir)
		}
		for _, dir := range opts.IncludeDest[t.Name] {
			includes = append(includes, underPrefix(dir))
		}
	}

	defines, err := ctx.evalGenexList(t.IfaceDefines)
	if err != nil {
		return nil, err
	}
	compileOpts, err := ctx.evalGenexList(t.IfaceCompileOpts)
	if err != nil {
		return nil, err
	}
	linkOpts, err := ctx.evalGenexList(t.IfaceLinkOpts)
	if err != nil {
		return nil, err
	}
	links, err := ctx.evalGenexList(t.IfaceLinkLibs)
	if err != nil {
		return nil, err
	}
	// A target in the same export set is referred to by its exported name: the
	// consumer will not have a plain "util", it will have "Demo::util".
	inSet := map[string]bool{}
	for _, m := range opts.Targets {
		inSet[m.Name] = true
	}
	for i, lib := range links {
		if inSet[lib] {
			links[i] = opts.Namespace + lib
		}
	}

	var out []exportProperty
	add := func(name string, values []string) {
		if len(values) > 0 {
			out = append(out, exportProperty{name, eval.JoinList(dedupe(values))})
		}
	}
	add("INTERFACE_COMPILE_DEFINITIONS", defines)
	add("INTERFACE_COMPILE_OPTIONS", compileOpts)
	add("INTERFACE_INCLUDE_DIRECTORIES", includes)
	add("INTERFACE_LINK_LIBRARIES", links)
	add("INTERFACE_LINK_OPTIONS", linkOpts)
	if len(t.IfaceCompileFeats) > 0 {
		add("INTERFACE_COMPILE_FEATURES", t.IfaceCompileFeats)
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out, nil
}

// artifactPaths is where the target's files are, in whichever tree applies.
func (e *Export) artifactPaths(t *eval.TargetState, opts exportOptions) (location, implib string) {
	if opts.Install {
		p := opts.Destinations[t.Name]
		return p.Location, p.Implib
	}
	built := targetOutputPath(t, e.Toolchain, e.SourceDir, e.BinaryDir)
	if t.Type == "SHARED" && e.Toolchain != nil && e.Toolchain.ImportSuffix != "" {
		return built, strings.TrimSuffix(built, e.Toolchain.SharedSuffix) + e.Toolchain.ImportSuffix
	}
	return built, ""
}

// underPrefix makes one directory relative to the computed install prefix.
func underPrefix(dir string) string {
	if strings.HasPrefix(dir, "${_IMPORT_PREFIX}") {
		return dir
	}
	return "${_IMPORT_PREFIX}/" + strings.TrimPrefix(dir, "/")
}

// InstallExport is what install(EXPORT) needs from the generator: the file to
// write into the build tree, and where the install script should put it.
type InstallExport struct {
	// StagedPath is where the file is written now, inside the build tree. It
	// is not the file a consumer reads; the install step copies it.
	StagedPath string
	Content    string
	// Destination is the directory under the install prefix it is copied to.
	Destination string
}

// InstallFiles renders the export file for every install(EXPORT) rule.
//
// The file is written into the build tree first and copied at install time
// rather than being written directly to the prefix, because the prefix is not
// known at generate time -- `cmake --install dir --prefix /somewhere` decides
// it. The paths inside are relative to whatever prefix turns out to be, which
// is what makes one staged file serve any prefix.
func (e *Export) InstallFiles() ([]InstallExport, error) {
	var out []InstallExport
	for _, rule := range e.Graph.State.InstallRules {
		if rule.Kind != "EXPORT" || rule.Export == "" {
			continue
		}
		names := e.setMembers(rule.Export)
		if len(names) == 0 {
			return nil, fmt.Errorf("install(EXPORT %s) names an export set no install(TARGETS) added to", rule.Export)
		}
		var targets []*eval.TargetState
		for _, name := range names {
			t, ok := e.Graph.target(name)
			if !ok {
				return nil, fmt.Errorf("install(EXPORT %s) names unknown target %q", rule.Export, name)
			}
			targets = append(targets, t)
		}
		opts := exportOptions{
			Targets:      targets,
			Namespace:    rule.Namespace,
			Install:      true,
			PrefixDepth:  prefixDepth(rule.Destination),
			IncludeDest:  e.includeDestinations(rule.Export),
			Destinations: e.installedDestinations(rule.Export),
		}
		text, err := e.render(opts)
		if err != nil {
			return nil, err
		}
		file := rule.File
		if file == "" {
			file = rule.Export + ".cmake"
		}
		out = append(out, InstallExport{
			StagedPath:  path.Join(e.BinaryDir, "CMakeFiles", "Export", rule.Export, file),
			Content:     text,
			Destination: rule.Destination,
		})
	}
	return out, nil
}

// prefixDepth counts how far a destination is below the install prefix, which
// is how many directories the generated file has to climb to find it again.
func prefixDepth(dest string) int {
	n := 0
	for _, part := range strings.Split(path.Clean(strings.Trim(dest, "/")), "/") {
		if part != "" && part != "." {
			n++
		}
	}
	return n
}

// includeDestinations collects install(TARGETS ... INCLUDES DESTINATION) per
// target, which is a usage requirement recorded on the install rule rather
// than on the target itself.
func (e *Export) includeDestinations(set string) map[string][]string {
	out := map[string][]string{}
	for _, rule := range e.Graph.State.InstallRules {
		if rule.Kind != "TARGETS" || rule.Export != set || len(rule.IncludeDest) == 0 {
			continue
		}
		for _, name := range rule.Items {
			out[name] = append(out[name], rule.IncludeDest...)
		}
	}
	return out
}

// installedDestinations works out where each target's files land, so the
// exported target can point at them. The answer has to agree with what the
// install script actually copies, so it is computed from the same rules.
func (e *Export) installedDestinations(set string) map[string]installedPaths {
	out := map[string]installedPaths{}
	in := &Install{Graph: e.Graph, Toolchain: e.Toolchain, SourceDir: e.SourceDir, BinaryDir: e.BinaryDir}
	for _, rule := range e.Graph.State.InstallRules {
		if rule.Kind != "TARGETS" || rule.Export != set {
			continue
		}
		for _, name := range rule.Items {
			r, ok := e.Graph.Targets[name]
			if !ok {
				continue
			}
			var p installedPaths
			for _, art := range in.artifactsOf(r.Target) {
				dest := artifactDestination(rule, art.keyword, r.Target.Type)
				full := "${_IMPORT_PREFIX}/" + path.Join(dest, path.Base(art.path))
				if art.keyword == "ARCHIVE" && r.Target.Type == "SHARED" {
					p.Implib = full
				} else {
					p.Location = full
				}
			}
			out[name] = p
		}
	}
	return out
}
