package generate

import (
	"fmt"
	"io"
	"path"
	"runtime"
	"sort"
	"strings"

	"github.com/vertex-language/go-cmake/eval"
	"github.com/vertex-language/go-cmake/toolchain"
)

// Installing is generated as a CMake script rather than done directly.
//
// CMake writes a cmake_install.cmake into the build tree and installs by
// running it, and copying that design here is not deference: the install rules
// were written in a language this package already evaluates, and the questions
// they raise -- which component, which configuration, what the prefix is -- are
// answered at install time, not at generate time. Writing a script defers them
// to the moment they can be answered, and makes `cmake --install` a `cmake -P`
// with three variables set.
//
// It also means the install step is inspectable. A build tree contains the
// exact list of what will be copied where, in a form a person can read.

// Install writes the install script for a resolved graph.
type Install struct {
	Graph     *Graph
	Toolchain *toolchain.Toolchain
	SourceDir string
	BinaryDir string
}

// Write emits the complete cmake_install.cmake.
//
// It is not called WriteTo: that name belongs to io.WriterTo, whose contract is
// to report the byte count, and nothing here counts bytes.
func (in *Install) Write(w io.Writer) error {
	var b strings.Builder
	b.WriteString("# Install script for " + in.SourceDir + "\n")
	b.WriteString("# Generated by go-cmake. Do not edit.\n\n")

	// The prefix, the configuration, and the component are the three things a
	// caller may choose at install time. Each is defaulted only if unset, so
	// `cmake --install dir --prefix /opt` works by setting one variable.
	b.WriteString(`if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "` + defaultPrefix(in.Graph.State) + `")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  set(CMAKE_INSTALL_CONFIG_NAME "")
endif()

if(NOT DEFINED CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_COMPONENT "")
endif()

`)

	for _, rule := range in.Graph.State.InstallRules {
		if err := in.writeRule(&b, rule); err != nil {
			return err
		}
	}

	// The manifest is what `--install` reports and what a packager reads.
	b.WriteString(`
if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "` + in.BinaryDir + `/${CMAKE_INSTALL_MANIFEST}" "${CMAKE_INSTALL_MANIFEST_CONTENT}")
`)

	_, err := io.WriteString(w, b.String())
	return err
}

// writeRule emits one install() directive.
func (in *Install) writeRule(b *strings.Builder, rule eval.InstallRule) error {
	// Every rule is guarded, including one that named no component: a rule
	// without a COMPONENT belongs to "Unspecified", and leaving it unguarded
	// would make `--install --component devel` install everything, which is the
	// opposite of what asking for one component means.
	component := rule.Component
	if component == "" {
		component = "Unspecified"
	}
	fmt.Fprintf(b, "if(CMAKE_INSTALL_COMPONENT STREQUAL %q OR NOT CMAKE_INSTALL_COMPONENT)\n", component)

	switch rule.Kind {
	case "TARGETS":
		in.writeTargets(b, rule)
	case "FILES", "PROGRAMS":
		in.writeFiles(b, rule)
	case "DIRECTORY":
		in.writeDirectories(b, rule)
	case "SCRIPT":
		for _, item := range rule.Items {
			fmt.Fprintf(b, "  include(%q)\n", in.absolute(rule.SourceDir, item))
		}
	case "CODE":
		for _, item := range rule.Items {
			// The code is CMake source the project wrote; it is emitted as
			// written rather than quoted, because quoting it would install a
			// string rather than run a command.
			b.WriteString("  " + item + "\n")
		}
	case "EXPORT":
		in.writeExport(b, rule)
	case "IMPORTED_RUNTIME_ARTIFACTS":
		fmt.Fprintf(b, "  # install(%s) is recorded but not generated\n", rule.Kind)
	}

	b.WriteString("endif()\n\n")
	return nil
}

func (in *Install) writeTargets(b *strings.Builder, rule eval.InstallRule) {
	for _, name := range rule.Items {
		r, ok := in.Graph.Targets[name]
		if !ok {
			// A target that does not exist is a project error, but reporting it
			// from the generated script keeps the message at the point of use.
			fmt.Fprintf(b, "  message(FATAL_ERROR \"install(TARGETS) given unknown target %s\")\n", name)
			continue
		}
		for _, art := range in.artifactsOf(r.Target) {
			dest := artifactDestination(rule, art.keyword, r.Target.Type)
			fmt.Fprintf(b, "  file(INSTALL DESTINATION %q TYPE %s %sFILES %q)\n",
				in.prefixed(dest), art.installType, optionalFlag(rule), art.path)
		}
	}
}

func (in *Install) writeFiles(b *strings.Builder, rule eval.InstallRule) {
	if len(rule.Items) == 0 {
		return
	}
	kind := "FILE"
	if rule.Kind == "PROGRAMS" {
		kind = "PROGRAM"
	}
	quoted := make([]string, 0, len(rule.Items))
	for _, item := range rule.Items {
		quoted = append(quoted, fmt.Sprintf("%q", in.absolute(rule.SourceDir, item)))
	}
	rename := ""
	if rule.Rename != "" {
		rename = fmt.Sprintf("RENAME %q ", rule.Rename)
	}
	fmt.Fprintf(b, "  file(INSTALL DESTINATION %q TYPE %s %s%sFILES %s)\n",
		in.prefixed(rule.Destination), kind, rename, optionalFlag(rule), strings.Join(quoted, " "))
}

func (in *Install) writeDirectories(b *strings.Builder, rule eval.InstallRule) {
	for _, item := range rule.Items {
		fmt.Fprintf(b, "  file(INSTALL DESTINATION %q TYPE DIRECTORY %sFILES %q)\n",
			in.prefixed(rule.Destination), optionalFlag(rule),
			strings.TrimSuffix(in.absolute(rule.SourceDir, item), "/"))
	}
}

func optionalFlag(rule eval.InstallRule) string {
	if rule.Optional {
		return "OPTIONAL "
	}
	return ""
}

// prefixed renders a destination relative to the install prefix, leaving an
// absolute destination alone -- which is how install(DESTINATION /etc) escapes
// the prefix, deliberately.
func (in *Install) prefixed(dest string) string {
	if dest == "" {
		dest = "."
	}
	if path.IsAbs(dest) || (len(dest) > 1 && dest[1] == ':') {
		return dest
	}
	return "${CMAKE_INSTALL_PREFIX}/" + strings.TrimPrefix(dest, "./")
}

func (in *Install) absolute(sourceDir, item string) string {
	item = strings.ReplaceAll(item, "\\", "/")
	if path.IsAbs(item) || (len(item) > 1 && item[1] == ':') {
		return item
	}
	return path.Join(strings.ReplaceAll(sourceDir, "\\", "/"), item)
}

// targetOutput is where the build put a target's file.
func (in *Install) targetOutput(t *eval.TargetState) string {
	return targetOutputPath(t, in.Toolchain, in.SourceDir, in.BinaryDir)
}

// installTypeFor is the TYPE keyword file(INSTALL) wants, which decides the
// permissions the installed file gets.
func installTypeFor(targetType string) string {
	switch targetType {
	case "EXECUTABLE":
		return "EXECUTABLE"
	case "SHARED", "MODULE":
		return "SHARED_LIBRARY"
	default:
		return "STATIC_LIBRARY"
	}
}

// defaultTargetDestination is where a target goes when install(TARGETS) names
// no destination. The split between bin and lib is the GNU convention CMake
// adopted, and a project that omits DESTINATION is asking for it.
func defaultTargetDestination(targetType string) string {
	switch targetType {
	case "EXECUTABLE":
		return "bin"
	case "SHARED", "MODULE":
		return "lib"
	default:
		return "lib"
	}
}

// defaultPrefix is where an install goes when nobody says. CMAKE_INSTALL_PREFIX
// set by the project wins; otherwise it is the platform convention.
func defaultPrefix(state *eval.State) string {
	if v := state.GetVar("CMAKE_INSTALL_PREFIX"); v != "" {
		return v
	}
	if entry, ok := state.Cache.Get("CMAKE_INSTALL_PREFIX"); ok && entry.Value != "" {
		return entry.Value
	}
	if runtime.GOOS == "windows" {
		return "C:/Program Files/" + projectName(state)
	}
	return "/usr/local"
}

func projectName(state *eval.State) string {
	if n := state.GetVar("CMAKE_PROJECT_NAME"); n != "" {
		return n
	}
	return "Project"
}

// InstalledFiles reports what the install script will copy, which is what a
// caller inspecting a configure result wants rather than the script text.
func (in *Install) InstalledFiles() []string {
	var out []string
	for _, rule := range in.Graph.State.InstallRules {
		switch rule.Kind {
		case "TARGETS":
			for _, name := range rule.Items {
				if r, ok := in.Graph.Targets[name]; ok {
					out = append(out, in.targetOutput(r.Target))
				}
			}
		case "FILES", "PROGRAMS", "DIRECTORY":
			for _, item := range rule.Items {
				out = append(out, in.absolute(rule.SourceDir, item))
			}
		}
	}
	sort.Strings(out)
	return out
}

// artifact is one file a target produces and one place install(TARGETS) may
// have been told to put it.
type artifact struct {
	path        string
	keyword     string // ARCHIVE, LIBRARY or RUNTIME
	installType string // the TYPE keyword file(INSTALL) wants
}

// artifactsOf lists what a target produces.
//
// A shared library on Windows produces two files, and they belong in different
// directories: the DLL goes next to the programs that load it and the import
// library goes with the other link-time files. Installing only one of them
// produces a package that either cannot be linked against or cannot be run.
func (in *Install) artifactsOf(t *eval.TargetState) []artifact {
	built := in.targetOutput(t)
	switch t.Type {
	case "EXECUTABLE":
		return []artifact{{built, "RUNTIME", "EXECUTABLE"}}
	case "SHARED", "MODULE":
		out := []artifact{{built, "RUNTIME", "SHARED_LIBRARY"}}
		if in.Toolchain != nil && in.Toolchain.ImportSuffix != "" {
			implib := strings.TrimSuffix(built, in.Toolchain.SharedSuffix) + in.Toolchain.ImportSuffix
			out = append(out, artifact{implib, "ARCHIVE", "STATIC_LIBRARY"})
		} else {
			// Everywhere else the one file is both what is linked and what is
			// loaded, so LIBRARY is the keyword that places it.
			out[0].keyword = "LIBRARY"
		}
		return out
	case "INTERFACE", "UTILITY", "OBJECT":
		return nil
	default:
		return []artifact{{built, "ARCHIVE", "STATIC_LIBRARY"}}
	}
}

// artifactDestination picks where one artifact goes: the keyword's own
// destination if the rule gave it one, then the rule's plain DESTINATION, then
// the convention.
func artifactDestination(rule eval.InstallRule, keyword, targetType string) string {
	if d, ok := rule.ArtifactDest[keyword]; ok && d != "" {
		return d
	}
	if rule.Destination != "" {
		return rule.Destination
	}
	if keyword == "RUNTIME" {
		return "bin"
	}
	return defaultTargetDestination(targetType)
}

// writeExport installs the staged targets file.
//
// The file itself was written during generation; all the install script has to
// do is copy it, which is why nothing here knows what is in it.
func (in *Install) writeExport(b *strings.Builder, rule eval.InstallRule) {
	file := rule.File
	if file == "" {
		file = rule.Export + ".cmake"
	}
	staged := path.Join(in.BinaryDir, "CMakeFiles", "Export", rule.Export, file)
	fmt.Fprintf(b, "  file(INSTALL DESTINATION %q TYPE FILE FILES %q)\n",
		in.prefixed(rule.Destination), staged)
}
