package generate

import (
	"fmt"
	"io"
	"path"
	"sort"
	"strings"

	"github.com/vertex-language/go-cmake/eval"
	"github.com/vertex-language/go-cmake/toolchain"
)

// Ninja writes a build.ninja for a resolved graph.
//
// The file it produces is a build system, not a script: every command is
// attached to the outputs it produces and the inputs it consumes, so that the
// build tool can decide what to run. That is the entire reason the generate
// phase exists as a separate step — a CMakeLists.txt describes intent, and
// intent cannot be made incremental.
type Ninja struct {
	Graph     *Graph
	Toolchain *toolchain.Toolchain
	BinaryDir string
	SourceDir string

	// CMakeCommand is the path to this program, which generated rules invoke
	// for portable file operations (`cmake -E touch` and friends). A generated
	// build file that assumed a `cmake` on PATH would break the moment the
	// build ran anywhere else.
	CMakeCommand string
}

// WriteTo emits the complete build.ninja.
func (n *Ninja) WriteTo(w io.Writer) (int64, error) {
	b := &ninjaWriter{w: w}
	b.comment("This file is generated by go-cmake. Do not edit.")
	b.line("ninja_required_version = 1.8")
	b.blank()

	b.variable("SOURCE_DIR", n.SourceDir)
	b.variable("BINARY_DIR", n.BinaryDir)
	b.blank()

	n.writeRules(b)

	if err := n.resolveGenex(); err != nil {
		return b.n, err
	}

	var all []string
	for _, name := range n.Graph.Order {
		outputs, err := n.writeTarget(b, name)
		if err != nil {
			return b.n, err
		}
		r := n.Graph.Targets[name]
		if len(outputs) > 0 && !r.Target.ExcludeAll {
			all = append(all, outputs...)
		}
	}

	n.writeCustomCommands(b)

	if len(all) > 0 {
		b.blank()
		b.line("build all: phony " + strings.Join(escapeAll(all), " "))
		b.line("default all")
	}
	return b.n, b.err
}

// resolveGenex evaluates the generator expressions in every target's settings.
//
// This happens here rather than during configure because the answers do not
// exist until now: $<TARGET_FILE:foo> is a path this generator chooses, and
// $<CONFIG:Release> is a question about a configuration the caller selects.
func (n *Ninja) resolveGenex() error {
	config := n.Graph.State.GetVar("CMAKE_BUILD_TYPE")
	for _, name := range n.Graph.Order {
		r := n.Graph.Targets[name]
		ctx := &genexContext{
			graph:  n.Graph,
			tc:     n.Toolchain,
			ninja:  n,
			target: r.Target,
			config: config,
		}
		var err error
		for _, field := range []*[]string{
			&r.IncludeDirs, &r.Defines, &r.CompileOpts,
			&r.LinkOpts, &r.LinkDirs, &r.LinkLibs,
		} {
			if *field, err = ctx.evalGenexList(*field); err != nil {
				return fmt.Errorf("target %q: %w", name, err)
			}
		}
		// Sources may name generated files through an expression too.
		if r.Target.Sources, err = ctx.evalGenexList(r.Target.Sources); err != nil {
			return fmt.Errorf("target %q sources: %w", name, err)
		}
	}
	return nil
}

// writeRules emits one compile rule per language plus the link rules. Rules are
// shared by every target, with the per-target differences carried in variables,
// which keeps the file proportional to the number of targets rather than to the
// number of source files.
func (n *Ninja) writeRules(b *ninjaWriter) {
	msvc := n.Toolchain.Kind() == toolchain.MSVC

	langs := make([]string, 0, len(n.Toolchain.Compilers))
	for lang := range n.Toolchain.Compilers {
		langs = append(langs, lang)
	}
	sort.Strings(langs)

	for _, lang := range langs {
		c := n.Toolchain.Compilers[lang]
		b.comment(lang + " compilation")
		if msvc {
			// /showIncludes makes cl report every header it opened; ninja parses
			// that output directly, which is why no depfile is needed.
			b.rule("compile_"+lang, map[string]string{
				"command":     fmt.Sprintf(`%s /nologo /showIncludes $DEFINES $INCLUDES $FLAGS /c $in /Fo$out`, quoteCommand(c.Path)),
				"description": "Building " + lang + " object $out",
				"deps":        "msvc",
			})
		} else {
			b.rule("compile_"+lang, map[string]string{
				"command":     fmt.Sprintf(`%s -MD -MF $out.d $DEFINES $INCLUDES $FLAGS -c $in -o $out`, quoteCommand(c.Path)),
				"description": "Building " + lang + " object $out",
				"depfile":     "$out.d",
				"deps":        "gcc",
			})
		}
		b.blank()
	}

	b.comment("Linking")
	if msvc {
		b.rule("archive", map[string]string{
			"command":     quoteCommand(n.Toolchain.Archiver) + " /nologo /OUT:$out $in",
			"description": "Linking static library $out",
		})
		b.rule("link_exe", map[string]string{
			"command":     quoteCommand(n.Toolchain.Linker) + " /nologo /OUT:$out $in $LINK_PATH $LINK_LIBS $LINK_FLAGS",
			"description": "Linking executable $out",
		})
		b.rule("link_shared", map[string]string{
			"command":     quoteCommand(n.Toolchain.Linker) + " /nologo /DLL /OUT:$out $in $LINK_PATH $LINK_LIBS $LINK_FLAGS",
			"description": "Linking shared library $out",
		})
	} else {
		b.rule("archive", map[string]string{
			// The archive is removed first because ar updates in place, and a
			// stale member left from a previous build would still be linked in.
			"command":     "rm -f $out && " + quoteCommand(n.Toolchain.Archiver) + " qc $out $in",
			"description": "Linking static library $out",
		})
		driver := n.linkDriver()
		b.rule("link_exe", map[string]string{
			"command":     quoteCommand(driver) + " $in -o $out $LINK_PATH $LINK_LIBS $LINK_FLAGS",
			"description": "Linking executable $out",
		})
		b.rule("link_shared", map[string]string{
			"command":     quoteCommand(driver) + " -shared $in -o $out $LINK_PATH $LINK_LIBS $LINK_FLAGS",
			"description": "Linking shared library $out",
		})
	}
	b.rule("custom", map[string]string{
		"command":     "$COMMAND",
		"description": "$DESC",
	})
	b.blank()
}

// linkDriver picks the compiler that drives linking. C++ is preferred when the
// project uses it, because linking C++ objects with the C driver omits the
// standard library and fails at the last possible moment.
func (n *Ninja) linkDriver() string {
	if c, ok := n.Toolchain.Compiler("CXX"); ok {
		return c.Path
	}
	if c, ok := n.Toolchain.Compiler("C"); ok {
		return c.Path
	}
	return "cc"
}

// writeTarget emits the compile and link edges for one target and returns the
// outputs that represent it.
func (n *Ninja) writeTarget(b *ninjaWriter, name string) ([]string, error) {
	r := n.Graph.Targets[name]
	t := r.Target

	if t.Imported {
		// An imported target names a file that already exists; nothing is built.
		return nil, nil
	}

	switch t.Type {
	case "INTERFACE":
		// Nothing to compile or link: an interface library is a bundle of
		// requirements, and it has already been folded into its consumers.
		return nil, nil
	case "UTILITY":
		return n.writeUtility(b, r)
	}

	objects, err := n.writeObjects(b, r)
	if err != nil {
		return nil, err
	}

	if t.Type == "OBJECT" {
		// An object library is its objects; consumers link them directly.
		return objects, nil
	}

	output := n.targetOutput(t)
	rule, extra := n.linkRuleFor(r)

	inputs := append([]string{}, objects...)
	// Object libraries this target links contribute their objects, not a file.
	for _, dep := range r.LinkLibs {
		if d, ok := n.Graph.target(dep); ok && d.Type == "OBJECT" {
			if dr, ok := n.Graph.Targets[d.Name]; ok {
				objs, err := n.objectPaths(dr)
				if err != nil {
					return nil, err
				}
				inputs = append(inputs, objs...)
			}
		}
	}

	var implicit []string
	for _, dep := range r.Deps {
		d, ok := n.Graph.target(dep)
		if !ok || d.Type == "INTERFACE" || d.Type == "OBJECT" || d.Imported {
			continue
		}
		implicit = append(implicit, n.targetOutput(d))
	}

	b.comment("target " + t.Name)
	b.buildEdge(output, rule, inputs, implicit, extra)
	// A named phony edge lets `ninja <target>` work the way `make <target>` does.
	b.line("build " + escape(t.Name) + ": phony " + escape(output))
	b.blank()
	return []string{output}, nil
}

// writeUtility emits an add_custom_target as a phony edge running its commands.
func (n *Ninja) writeUtility(b *ninjaWriter, r *Resolved) ([]string, error) {
	t := r.Target
	stamp := path.Join(n.BinaryDir, "CMakeFiles", t.Name+".stamp")

	var parts []string
	for _, cmd := range t.Commands {
		parts = append(parts, joinCommand(cmd))
	}
	// The stamp is touched last so the target is only up to date once every
	// command has succeeded.
	parts = append(parts, n.touchCommand(stamp))

	var implicit []string
	for _, dep := range t.Depends {
		if d, ok := n.Graph.target(dep); ok && !d.Imported && d.Type != "INTERFACE" {
			implicit = append(implicit, n.targetOutput(d))
		}
	}

	b.comment("custom target " + t.Name)
	desc := t.Properties["COMMENT"]
	if desc == "" {
		desc = "Running " + t.Name
	}
	b.buildEdge(stamp, "custom", nil, implicit, map[string]string{
		"COMMAND": strings.Join(parts, " && "),
		"DESC":    desc,
	})
	b.line("build " + escape(t.Name) + ": phony " + escape(stamp))
	b.blank()
	return []string{stamp}, nil
}

// writeObjects emits one compile edge per source file.
func (n *Ninja) writeObjects(b *ninjaWriter, r *Resolved) ([]string, error) {
	t := r.Target
	var objects []string
	for _, src := range t.Sources {
		abs := t.ResolveSource(src)
		lang := toolchain.LanguageOf(abs)
		if lang == "" {
			// Headers and data files are listed as sources so they appear in
			// IDEs; they are not compiled.
			continue
		}
		if _, ok := n.Toolchain.Compiler(lang); !ok {
			return nil, fmt.Errorf("no %s compiler was found, but target %q has %s sources", lang, t.Name, lang)
		}
		obj := n.objectPath(t, abs)
		b.buildEdge(obj, "compile_"+lang, []string{abs}, nil, map[string]string{
			"DEFINES":  n.defineFlags(r.Defines),
			"INCLUDES": n.includeFlags(r.IncludeDirs),
			"FLAGS":    strings.Join(r.CompileOpts, " "),
		})
		objects = append(objects, obj)
	}
	return objects, nil
}

// objectPaths recomputes a target's object list without re-emitting its edges.
func (n *Ninja) objectPaths(r *Resolved) ([]string, error) {
	var out []string
	for _, src := range r.Target.Sources {
		abs := r.Target.ResolveSource(src)
		if toolchain.LanguageOf(abs) == "" {
			continue
		}
		out = append(out, n.objectPath(r.Target, abs))
	}
	return out, nil
}

// objectPath places an object file under the target's own directory in the
// build tree, mirroring the source's path so that two sources with the same
// base name in different directories do not collide.
func (n *Ninja) objectPath(t *eval.TargetState, source string) string {
	rel := relativeTo(n.SourceDir, source)
	if rel == "" {
		rel = relativeTo(n.BinaryDir, source)
	}
	if rel == "" {
		// A source from outside both trees keeps only its base name, prefixed
		// so that two such sources still differ.
		rel = "external/" + path.Base(source)
	}
	return path.Join(n.BinaryDir, "CMakeFiles", t.Name+".dir", rel+n.Toolchain.ObjectSuffix)
}

// targetOutput is the file a target produces.
func (n *Ninja) targetOutput(t *eval.TargetState) string {
	dir := path.Join(n.BinaryDir, relativeTo(n.SourceDir, t.SourceDir))
	name := t.Name
	if v, ok := t.Properties["OUTPUT_NAME"]; ok && v != "" {
		name = v
	}
	tc := n.Toolchain
	switch t.Type {
	case "EXECUTABLE":
		return path.Join(dir, name+tc.ExeSuffix)
	case "SHARED", "MODULE":
		return path.Join(dir, tc.SharedPrefix+name+tc.SharedSuffix)
	default:
		return path.Join(dir, tc.StaticPrefix+name+tc.StaticSuffix)
	}
}

// linkRuleFor chooses the link rule and its per-target variables.
func (n *Ninja) linkRuleFor(r *Resolved) (string, map[string]string) {
	t := r.Target
	vars := map[string]string{}
	switch t.Type {
	case "STATIC":
		return "archive", vars
	case "SHARED", "MODULE":
		vars["LINK_PATH"] = n.linkPathFlags(r.LinkDirs)
		vars["LINK_LIBS"] = n.linkLibFlags(r)
		vars["LINK_FLAGS"] = strings.Join(r.LinkOpts, " ")
		return "link_shared", vars
	default:
		vars["LINK_PATH"] = n.linkPathFlags(r.LinkDirs)
		vars["LINK_LIBS"] = n.linkLibFlags(r)
		vars["LINK_FLAGS"] = strings.Join(r.LinkOpts, " ")
		return "link_exe", vars
	}
}

func (n *Ninja) defineFlags(defines []string) string {
	prefix := "-D"
	if n.Toolchain.Kind() == toolchain.MSVC {
		prefix = "/D"
	}
	var out []string
	for _, d := range defines {
		out = append(out, prefix+d)
	}
	return strings.Join(out, " ")
}

func (n *Ninja) includeFlags(dirs []string) string {
	prefix := "-I"
	if n.Toolchain.Kind() == toolchain.MSVC {
		prefix = "/I"
	}
	var out []string
	for _, d := range dirs {
		out = append(out, prefix+quoteArg(d))
	}
	// The toolchain's own headers come last, so a project's include path can
	// shadow a system header rather than the other way round.
	for _, d := range n.Toolchain.SystemIncludes() {
		out = append(out, prefix+quoteArg(d))
	}
	return strings.Join(out, " ")
}

func (n *Ninja) linkPathFlags(dirs []string) string {
	msvc := n.Toolchain.Kind() == toolchain.MSVC
	var out []string
	add := func(d string) {
		if msvc {
			out = append(out, "/LIBPATH:"+quoteArg(d))
		} else {
			out = append(out, "-L"+quoteArg(d))
		}
	}
	for _, d := range dirs {
		add(d)
	}
	for _, d := range n.Toolchain.SystemLibDirs() {
		add(d)
	}
	return strings.Join(out, " ")
}

// linkLibFlags renders the link line. A dependency that is a target becomes the
// file it produces; anything else is passed to the linker as written, because
// a project that wrote `m` means -lm and one that wrote an absolute path means
// that file.
func (n *Ninja) linkLibFlags(r *Resolved) string {
	msvc := n.Toolchain.Kind() == toolchain.MSVC
	var out []string
	for _, lib := range r.LinkLibs {
		if t, ok := n.Graph.target(lib); ok {
			switch {
			case t.Type == "OBJECT" || t.Type == "INTERFACE":
				continue // already contributed as objects or as requirements
			case t.Imported:
				if loc, ok := t.Properties["IMPORTED_LOCATION"]; ok {
					out = append(out, quoteArg(loc))
				}
				continue
			}
			out = append(out, quoteArg(n.linkFileFor(t)))
			continue
		}
		switch {
		case strings.HasPrefix(lib, "-") || strings.HasPrefix(lib, "/"):
			out = append(out, lib) // an explicit linker flag
		case strings.ContainsAny(lib, "/\\") || strings.Contains(lib, "."):
			out = append(out, quoteArg(lib)) // a path to a library file
		case msvc:
			out = append(out, lib+".lib")
		default:
			out = append(out, "-l"+lib)
		}
	}
	return strings.Join(out, " ")
}

// linkFileFor is the file a consumer links against, which on Windows is the
// import library rather than the DLL itself.
func (n *Ninja) linkFileFor(t *eval.TargetState) string {
	out := n.targetOutput(t)
	if (t.Type == "SHARED" || t.Type == "MODULE") && n.Toolchain.ImportSuffix != "" {
		return strings.TrimSuffix(out, n.Toolchain.SharedSuffix) + n.Toolchain.ImportSuffix
	}
	return out
}

// writeCustomCommands emits the add_custom_command(OUTPUT ...) rules.
func (n *Ninja) writeCustomCommands(b *ninjaWriter) {
	for _, cc := range n.Graph.State.CustomCommands {
		if len(cc.Outputs) == 0 {
			continue
		}
		var parts []string
		for _, cmd := range cc.Commands {
			parts = append(parts, joinCommand(cmd))
		}
		desc := cc.Comment
		if desc == "" {
			desc = "Generating " + path.Base(cc.Outputs[0])
		}
		b.comment("custom command")
		b.buildEdge(cc.Outputs[0], "custom", cc.Depends, nil, map[string]string{
			"COMMAND": strings.Join(parts, " && "),
			"DESC":    desc,
		})
		b.blank()
	}
}

// ----------------------------------------------------------------------------
// Ninja file syntax

type ninjaWriter struct {
	w   io.Writer
	n   int64
	err error
}

func (b *ninjaWriter) write(s string) {
	if b.err != nil {
		return
	}
	k, err := io.WriteString(b.w, s)
	b.n += int64(k)
	b.err = err
}

func (b *ninjaWriter) line(s string)    { b.write(s + "\n") }
func (b *ninjaWriter) blank()           { b.write("\n") }
func (b *ninjaWriter) comment(s string) { b.line("# " + s) }

func (b *ninjaWriter) variable(name, value string) {
	b.line(name + " = " + value)
}

func (b *ninjaWriter) rule(name string, vars map[string]string) {
	b.line("rule " + name)
	for _, k := range sortedKeys(vars) {
		if vars[k] != "" {
			b.line("  " + k + " = " + vars[k])
		}
	}
}

// buildEdge writes one build statement.
func (b *ninjaWriter) buildEdge(output, rule string, inputs, implicit []string, vars map[string]string) {
	line := "build " + escape(output) + ": " + rule
	if len(inputs) > 0 {
		line += " " + strings.Join(escapeAll(inputs), " ")
	}
	if len(implicit) > 0 {
		line += " | " + strings.Join(escapeAll(implicit), " ")
	}
	b.line(line)
	for _, k := range sortedKeys(vars) {
		if vars[k] != "" {
			b.line("  " + k + " = " + vars[k])
		}
	}
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// escape quotes a path for a ninja build statement, where a space separates
// inputs, a colon separates outputs from the rule, and '$' introduces a
// variable.
func escape(p string) string {
	r := strings.NewReplacer("$", "$$", " ", "$ ", ":", "$:")
	return r.Replace(p)
}

func escapeAll(paths []string) []string {
	out := make([]string, len(paths))
	for i, p := range paths {
		out[i] = escape(p)
	}
	return out
}

// quoteArg quotes a path for the shell that runs a command. Only a space needs
// it; quoting unconditionally would break flags that embed their own quoting.
func quoteArg(s string) string {
	if s == "" || !strings.ContainsAny(s, " \t") {
		return s
	}
	return `"` + s + `"`
}

// quoteCommand quotes an executable path for use at the front of a command.
func quoteCommand(s string) string {
	if s == "" {
		return s
	}
	return quoteArg(s)
}

// joinCommand renders an argv as a shell command line.
func joinCommand(argv []string) string {
	out := make([]string, len(argv))
	for i, a := range argv {
		out[i] = quoteArg(a)
	}
	return strings.Join(out, " ")
}

// touchCommand produces a portable "create or update this file" command.
func (n *Ninja) touchCommand(p string) string {
	cmake := n.CMakeCommand
	if cmake == "" {
		cmake = "cmake"
	}
	return quoteCommand(cmake) + " -E touch " + quoteArg(p)
}

// relativeTo returns target relative to base with forward slashes, or "" when
// target is not below base.
func relativeTo(base, target string) string {
	base = strings.TrimSuffix(strings.ReplaceAll(base, "\\", "/"), "/")
	target = strings.ReplaceAll(target, "\\", "/")
	if base == "" {
		return target
	}
	if strings.EqualFold(target, base) {
		return ""
	}
	if len(target) > len(base) && target[len(base)] == '/' &&
		strings.EqualFold(target[:len(base)], base) {
		return target[len(base)+1:]
	}
	return ""
}
